export const carsList = [
  {
    id: '1',
    brand: 'Toyota',
    model: 'Hilux',
    complect: 'Comfort',
    count: '52 авто',
    pricefrom: ' от 2 306 000 ₽',
    engine: 'Дизель, 2.8 л',
    engineHp: '177 л.с.',
    driveType: '4х4',
    driveDirection: 'Полный',
    transmissionType: 'АКПП',
    transmissionQuantity: '6 ступеней',
    price: 2390000,
    imgSrc: 'assets/img/hilux.jpg',
    discount: 200000,
    dealerAddress: 'Екатеринбург, ул. Восточная, 1',
    dealerPhone: '+7 (343) 222-00-44',
  },

  {
    id: '2',
    brand: 'Toyota',
    model: 'Land Cruiser 200',
    complect: 'Prestige',
    count: '86 авто',
    pricefrom: 'от 4 875 000 ₽',
    engine: 'Бензин, 4.7 л',
    engineHp: '309 л.с. ',
    driveType: '4х4',
    driveDirection: 'Полный',
    transmissionType: 'АКПП',
    transmissionQuantity: '6 ступеней',
    price: 5139000,
    imgSrc: 'assets/img/lc200.jpg',
    discount: 200000,
    dealerAddress: 'Екатеринбург, ул. Восточная, 1',
    dealerPhone: '+7 (343) 222-00-44',
  },

  {
    id: '3',
    brand: 'Toyota',
    model: 'Fortuner',
    complect: 'TRD',
    count: '17 авто',
    pricefrom: 'от 2 172 000 ₽',
    engine: 'Дизель, 2.8 л',
    engineHp: '177 л.с.',
    driveType: '4х4',
    driveDirection: 'Полный',
    transmissionType: 'АКПП',
    transmissionQuantity: '6 ступеней',
    price: 2951000,
    imgSrc: 'assets/img/fortuner.jpg',
    discount: 200000,
    dealerAddress: 'Екатеринбург, ул. Восточная, 1',
    dealerPhone: '+7 (343) 222-00-44',
  },
];
